### PR TITLE
Improve home cards

### PR DESCRIPTION
**Pull request by thibaultboursier**
- Use `ReignCard` component for each reign component, rather using duplicated card code.
- Improve `ReignCard` component, by removing useless padding on `Link` container and adding correct margins.
- Improve design, with a background image.
- Improve header spacing.

**Design**
Capture d’écran 2021-06-27 à 23 14 44

### CODE REVIEW

**Comment by hdorgeval** [comment]
Hi @thibaultboursier : The markup for the reign card could be simplified in a way that is fully compliant with bs5 and that will enable Gatsby to produce a progressive download of  the background image. 

Here is my proposal in vanilla html:

```html
<div class="card text-center bg-dark text-light border-secondary ratio ratio-16x9 mb-4" >
          <img src="background-card.jpg" class="card-img" alt="..." >
          <div class="card-img-overlay" style="background: linear-gradient(to bottom,rgba(0, 0, 0, 0.8), rgba(117, 19, 93, 0.30));">
            <div class="card-body card-text h-75">
              <h3 class="card-title fs-5">Djemschid</h3>
              <p class="card-text">Son règne dura 700 ans.</p>
            </div>
            <div class="card-footer text-light border-0 position-absolute start-0 bottom-0">
              <span>4 épisodes</span>
            </div>
          </div>
          
        </div>
```

Screen Shot 2021-06-29 at 00 28 57

**Comment by hdorgeval** [comment]
Hi @thibaultboursier : I notice you have modified the following markup:

```html
<h4 className="card-title">{cardTitle}</h4>
```

It was before 

```html
<h3 className="card-title fs-5">{cardTitle}</h3>
```

Your change has a negative impact on accessibility:
Screen Shot 2021-06-29 at 01 22 13

**Comment by hdorgeval** [comment]
Hi @thibaultboursier : I have also notice you have made a change in the home layout:

Screen Shot 2021-06-29 at 01 40 29

This change is great, because you got rid of the horizontal scroll bar.
Personaly I think that the space between the top part and the beginning of the text is too big:

Screen Shot 2021-06-29 at 01 44 56

**Comment by hdorgeval** [comment]
Hi @thibaultboursier, you have done a very interesting proposal in this PR.

I would like to incorporate your changes with my above remarks. And I will also configure the background image to be a local image that is progressively downloaded by Gatsby.

Would you let me finish this PR?

Thanks!

**Comment by thibaultboursier** [comment]
Hi @hdorgeval,

Thanks for your feedback.
Of course, feel free to finish this PR.
Don't hesitate to ask me if you need some changes on it.

**Comment by thibaultboursier** [comment]
> Hi @thibaultboursier : I notice you have modified the following markup:
> 
> ```
> <h4 className="card-title">{cardTitle}</h4>
> ```
> 
> It was before
> 
> ```
> <h3 className="card-title fs-5">{cardTitle}</h3>
> ```
> 
> Your change has a negative impact on accessibility:
> Screen Shot 2021-06-29 at 01 22 13

Yes, you are right. We should keep the previous tag and apply the specific font size that we want on it, without relying on tag to style it.

**Comment by hdorgeval** [comment]
Hi @thibaultboursier , I need to know where is the source for the background image, so that I can give credit for it in the about page.
Thanks.

**Pull request merged**
